### ISSUE TITLE
Event title is being stored in the date attribute for Events

### ISSUE THREAD

**Issue by AndrewERAU** [AndrewERAU/Calendar#36]
Error:
```error
date - Meeting to go over plan details.
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 32
	at java.lang.String.charAt(String.java:658)
	at time.Time.getDateFormat(Time.java:380)
	at time.Time.getWeekdayFromString(Time.java:238)
	at event.Event.formatEventSummary(Event.java:122)
	at views.Home_View.displayEventsForToday(Home_View.java:462)
	at views.Home_View.initUI(Home_View.java:151)
	at views.Home_View.<init>(Home_View.java:69)
	at views.Home_View.main(Home_View.java:73)
```

**Comment by AndrewERAU** [comment]
Looks like an error in db manager class for retrieve events method with flag 'D'

**Comment by AndrewERAU** [comment]
`createListOfEvents` was part of the bug.  The SQL statement was changed from specifying all the columns selected to just a `SELECT * FROM EVENTS ...`.  However, the `createListOfEvents` function still took the first value and put in in the first field for the Event object.  This caused the eventID column (in the db, but not in Event object) to be inserted into the event title, and all the attributes were off by 1 when getting the values they needed.

**Comment by AndrewERAU** [comment]
fixed
